apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: motorsport
  POSTGRES_USER: pg_user
  POSTGRES_PASSWORD: pg_passwd
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: db_user
  DB_USER: db_passwd
  DB_PASSWORD: pitwall