[ubuntu_server]
ubuntu-server ansible_connection=local

[azure_agent]
motorsport-agent ansible_host=4.223.143.190 ansible_user=azureuser ansible_ssh_private_key_file=~/.ssh/azure_motorsport

[all:vars]
ansible_python_interpreter=/usr/bin/python3
admin_user=opsadmin